### ISSUE TITLE
[Beam to Beam End Plate] Module can't be opened from the 'Recently Used Modules' list

### ISSUE THREAD

**Issue by sumagnadas** [mhsuhail00/Osdag#60]
## Overview
When you try to open "Beam to Beam End Plate Connection" module from the "Recently Used Modules", it doesn't open

## Module
Beam to Beam End Plate

## OS
Ubuntu 24.04
##Branch
test
Latest commit: ec4820e

## Steps to reproduce
1) Open OSDAG
2) Try opening Beam-to-Beam End Plate from the Recently Used Modules list
3) Doesn't open

## Expected behaviour
The module should open when clicked in the list.

## Video demonstration
https://github.com/user-attachments/assets/15d8b46b-3def-4fa8-bd05-215e27c5f280

**Comment by parthckaria** [comment]
I was able to reproduce this. I was not able to open this module from recent projects.

**Comment by mhsuhail00** [comment]
Fixed the issue

**Comment by mhsuhail00** [comment]
@sumagnadas 
Please recheck the issue.
It would be great if you check for all the implemented modules.

"Fin Plate"
"Cleat Angle"
"Header Plate"
"Seated Angle"
"End Plate"
"Plate Girder"
"Bolted to End Gusset"
"Welded to End Gusset"
"Lap Joint Welded"
"Lap Joint Bolted"
"Butt Joint Bolted"
"Butt Joint Welded"
"Column"
"Cover Plate Welded"
"Cover Plate Bolted"
"Beam Beam End Plate"
"Column End Plate"
"Column Cover Plate Bolted"
"Column Cover Plate Welded"
"Struts in Trusses"

**Comment by Zehen-249** [comment]
Checked in windows. No issue found

**Comment by AjinkyaDahale** [comment]
This works with (K)Ubuntu 25.10. But it still crashed as per another issue [#59].

**Comment by parthckaria** [comment]
@AjinkyaDahale close this issue if you feel it is resolved.
